export const EJES_ARTICULADORES: any = {
  Inclusión:
    "Este eje señala que es fundamental ir más allá de la idea de que la inclusión se reduce a incorporar a los grupos de la sociedad a la escuela, lo cual es muy importante, pero no es suficiente. Pensar la inclusión desde una perspectiva decolonial implica que los niños, niñas y adolescentes se formen en espacios educativos en los que sean conscientes de que, si falta una o uno por motivos de clase, sexo, género, etnia, lengua, cultura, capacidad, condición migratoria o religión, entonces no están incluidos todos ni todas. Con lo anterior se trata de que la escuela construya una perspectiva comunitaria en donde las acciones individuales y colectivas en zonas urbanas y rurales con el acompañamiento de las familias; las reuniones de Consejo Técnico Escolar; el trabajo colegiado de las maestras y los maestros; el uso de los espacios escolares empezando por el aula, talleres y laboratorios, así como las relaciones pedagógicas estén enfocadas en la inclusión.",
  "Pensamiento crítico":
    "El eje articulador de pensamiento crítico, en donde lo crítico se entiende como la recuperación del otro desde la diversidad, es fundamental para la formación de una ciudadanía con valores democráticos y justicia social. Una primera tarea del pensamiento crítico es propiciar en las y los estudiantes de la educación básica un desarrollo gradual de capacidades para entender y analizar la complejidad de su mundo inmediato, de las personas y sus experiencias como acciones que actúan de manera conjunta e influyen entre sí.",
  "Interculturalidad Crítica":
    "Este eje articulador parte de que las culturas son matrices dinámicas y complejas de producción de imaginación, creencia, comprensión, interpretación y acción que las personas y los grupos construyen e interiorizan para dar sentido y razón a su vida, a su comunidad y a los contextos geográficos y sociales en que habitan. Las culturas generan tipos específicos de subjetividad, formas originales de ser humano, que a su vez producen, crean y recrean esas mismas culturas. La interculturalidad se refiere a sujetos, comunidades e identidades lingüísticas, culturales, sociales y territoriales en su diversidad, que interactúan, dialogan, se interpelan y producen entre sí diferentes realidades en un marco de relaciones asimétricas. Pensar la educación preescolar, primaria y secundaria desde la interculturalidad supone para todas y todos que es posible enseñar y aprender conocimientos y saberes desde diversos fundamentos conceptuales que permiten a las y los estudiantes pensarse a sí mismas y a sí mismos, en coexistencia con los otros y el medio ambiente.",
  "Igualdad de género":
    "La incorporación de un eje sobre igualdad de género en la educación preescolar, primaria y secundaria supone una formación en la que niñas, niños y adolescentes cuestionen prácticas institucionalizadas desde donde se asigna a cada persona una identidad sexual, racial y un género que termina estableciendo desigualmente su condición laboral, social y educativa en la comunidad o fuera de ésta. Se necesita abrir espacios de reflexión en las escuelas para que niñas, niños y adolescentes puedan comprender que la igualdad de género es una condición histórica, no un rasgo cultural de la sociedad, por lo que la violencia en contra de las mujeres se ejerce a partir de un conjunto de desigualdades sociales, económicas, étnicas, lingüísticas, territoriales que se basan en una inexistente desigualdad biológica.",
  "Vida saludable":
    "Este eje procura introducir en la vida escolar la comprensión de que salud humana y medio ambiente son organismos vivos interdependientes; el cuidado de uno tiene efectos positivos en otras personas y viceversa. Existe un circulo vital entre las actividades humanas: producción energética, extracción de minerales, actividad industrial y agropecuaria; el medio ambiente: suelo, aire, clima, agua, flora, fauna, etcétera, y la salud de las personas. El principio fundamental de una vida saludable vinculada al medio ambiente radica en que todas y todos somos seres humanos que convivimos en el planeta Tierra con otros seres vivientes: animales, plantas y seres inanimados con los que tenemos una responsabilidad ineludible e intransferible, con los que conformamos una comunidad planetaria.",
  "Apropiación de las culturas a través de la lectura y la escritura":
    "La lectura y la escritura son prácticas que contribuyen a hacer de la escuela una comunidad de lectoras y lectores que se acercan a los textos para comprender algo de su mundo cotidiano, para conocer otros modos de vida, para descubrir otras formas de utilizar el lenguaje y darles nuevos sentidos o defender su propio pensamiento a través de la producción de textos. La escolarización de las prácticas sociales de lectura y escritura requiere construir puentes curriculares cuyos contenidos guarden relación entre lo que se enseña y aprende en la escuela con la forma en que se viven fuera de ella, en la comunidad. La propuesta didáctica parte de la experiencia de las maestras y los maestros y vincula a la escuela con la sociedad a través de proyectos de servicio hacia la comunidad.",
  "Artes y experiencias estéticas":
    "Este eje busca valorar la exploración sensible del mundo al reconocer y recuperar el valor formativo de las experiencias artísticas y estéticas que se producen en las y los estudiantes en su relación con las manifestaciones culturales, las producciones del arte y la naturaleza, así como en el reconocimiento de las artes como expresión, cultura, comunicación y cognición, abriendo puentes con otras formas de conocimiento inalienables de la experiencia humana. Las artes como sistema cultural ofrecen a las y los estudiantes la posibilidad de crear relaciones con el mundo que atienden a los aspectos reflexivos y afectivos; encontrar otras formas de comunicación; imaginar y preguntarse sobre lo que puede ser; abrir nuevos mundos de pensamiento y sensibilidad con la finalidad de contribuir al reconocimiento de nuestro “paisaje interior” y a una mejor relación con la comunidad desde lo sensible, lo plural y el ejercicio del pensamiento crítico. Habrá que decir también que las artes hacen parte del derecho de niñas, niños y adolescentes a gozar de las experiencias estéticas para establecer espacios de diálogo en torno a temas y problemas de interés común que son parte de las ciencias, tanto sociales como naturales, así como de las humanidades.",
};
export const EJES_VIDEOS: any = {
  Inclusión: "https://youtube.com/embed/zkx2y6hG_kA",
  "Pensamiento crítico": "https://youtube.com/embed/IbtLzJ72Gfs",
  "Interculturalidad Crítica": "https://youtube.com/embed/dYvsHaDu_ps",
  "Igualdad de género": "https://youtube.com/embed/-qAMeSGfrDA",
  "Vida saludable": "https://youtube.com/embed/sqQySjk2e-I",
  "Apropiación de las culturas a través de la lectura y la escritura": "https://youtube.com/embed/sFR7THv9MEE",
  "Artes y experiencias estéticas": "https://youtube.com/embed/DwOErMC91JM",
};

export const EJES_ARTICULADORES_ARR: any = [
  "Inclusión",
  "Pensamiento crítico",
  "Interculturalidad Crítica",
  "Igualdad de género",
  "Vida saludable",
  "Apropiación de las culturas a través de la lectura y la escritura",
  "Artes y experiencias estéticas",
];
